### ISSUE TITLE
file bat fail!...

### ISSUE THREAD

**Issue by gearcapitan** [r00t-3xp10it/Meterpreter_Paranoid_Mode-SSL#1]
![kali linux-2017-05-13-20-05-32](https://cloud.githubusercontent.com/assets/13740942/26030376/a53e4f3a-3817-11e7-9df6-5ea6e79ff8cc.png)

**Comment by r00t-3xp10it** [comment]
**ERROR: The sellected arch is incompatible with the payload sellected ...**

    Is your systems '32 bits' and you have selected a '64 bits payload'?
    I have released just now (after this bug report) a new commit
    '64 bits archs support' download the tool and try again ..

P.S Inform me what is your **system arch** (32 OR 64)
payload you are trying to use: **windows/x64/meterpreter/reverse_https** (staged)
HINT: 32 bits payload works perfectlly fine under 64 bits archs  :v:
