### ISSUE TITLE
how to remove tool?

### ISSUE THREAD

**Issue by gearcapitan** [r00t-3xp10it/Meterpreter_Paranoid_Mode-SSL#2]
![kali linux-2017-05-14-16-46-34](https://cloud.githubusercontent.com/assets/13740942/26038073/a20147f6-38c5-11e7-8855-f59a616b7ebb.png)
se que parece que no tiene nada que ver, pero ahora tengo conflicto con ejecutar cobaltstrike por el certificado que genera el Meterpreter_Paranoid_Mode, algun consejo?

**Comment by r00t-3xp10it** [comment]
yap it was nothing to do with meterpreter_paranoid_mode tool ..
**"The certificate created or used by my tool was nothing to do with this error"**

The tool **does not change SSL settings**, it only builds the
certificate using **openssl** or one **metasploit auxiliary module** ...

the certificate its stored inside tool/output folder ...
**"Its not ported to any other place"...**
