### ISSUE TITLE
Session closed in meterpreter

### ISSUE THREAD

**Issue by eventises** [r00t-3xp10it/Meterpreter_Paranoid_Mode-SSL#7]
Detected by kspky
once I'm connected to meterpreter kspky AV detect the meterpreter calls﻿

**Comment by r00t-3xp10it** [comment]
Thats bad news ..

1º - did you used **staged ps1** payload (further obfuscated in base64 )
2º - did you used **winhttps** payload (its requied to SSL pinning to work)

3º - Also in tool activate the follow configs in the '**settings**' file:

    ENCODER_INTERACTIONS=3 <--- chose a bigger numbers of interactions
    ENABLE_STAGE_ENCODING=true <-- enable stage encoding (sending stage to: ..)

<br />

### Final notes:
If you used all the above settings then dont blame my tool of kaspersky detection
**(meterpreter remote executed commands beeing flaged)** ..

**Lets ty to fix the detection ...**
